version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: bce_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bce_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: bce_backend
    restart: always
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/bce_db
      - SECRET_KEY=your_secret_key_here
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bce_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
